#ifndef _COMPLIANCE_MODEL_H
#define _COMPLIANCE_MODEL_H

#define BUGGYV_SIGNATURE_ADDR
#define BUGGYV_STATUS_ADDR
#define BUGGYV_PASS_CODE
#define BUGGYV_FAIL_CODE

#define RVMODEL_DATA_SECTION
#define RVMODEL_BOOT

#define RVMODEL_ACCESS_FAULT_ADDRESS

#define RVMODEL_IO_INIT(_R1, _R2, _R3)
#define RVMODEL_IO_WRITE_STR(_R1, _R2, _R3, _STR_PTR)

#define RVMODEL_HALT_PASS
#define RVMODEL_HALT_FAIL

#define RVMODEL_MTIME_ADDRESS
#define RVMODEL_MTIMECMP_ADDRESS
#define RVMODEL_TIMER_INT_SOON_DELAY

#define RVMODEL_SET_MEXT_INT(_R1, _R2)
#define RVMODEL_CLR_MEXT_INT(_R1, _R2)
#define RVMODEL_SET_MSW_INT(_R1, _R2)
#define RVMODEL_CLR_MSW_INT(_R1, _R2)
#define RVMODEL_SET_SEXT_INT(_R1, _R2)
#define RVMODEL_CLR_SEXT_INT(_R1, _R2)
#define RVMODEL_SET_SSW_INT(_R1, _R2)
#define RVMODEL_CLR_SSW_INT(_R1, _R2)

#endif
